spring: 
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_taxtech
    username: root
    password: root123123
    driver-class-name: com.mysql.cj.jdbc.Driver



#spring.jpa.show-sql: true




