server:
  port: 8081 

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wsa01/microservice.git
          searchPaths: config-data
          username: wsa01
          password: Billy199459_GH
          
  security:
    user:
      name: root
      password: secret