server:
  port: 8080

spring:
  config:
    import:
    - "optional:configserver:http://localhost:8081"

#spring:
#  application:
#    name: customer-service
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: secret